version: 2
updates:
- package-ecosystem: "npm"
  directory: "/hirpc"
  schedule:
    interval: "quarterly"
  open-pull-requests-limit: 10
  labels:
    - "scope:hirpc"
    - "dependencies"
  target-branch: "dev"
