
namespace Dissonity.Models
{
    public enum PermissionFlags : long
    {
        CreateInstantInvite = 1 << 0,
        KickMembers = 1 << 1,
        BanMembers = 1 << 2,
        Administrator = 1 << 3,
        ManageChannels = 1 << 4,
        ManageGuild = 1 << 5,
        AddReactions = 1 << 6,
        ViewAuditLog = 1 << 7,
        PrioritySpeaker = 1 << 8,
        Stream = 1 << 9,
        ViewChannel = 1 << 10,
        SendMessages = 1 << 11,
        SendTtsMessages = 1 << 12,
        ManageMessages = 1 << 13,
        EmbedLinks = 1 << 14,
        AttachFiles = 1 << 15,
        ReadMessageHistory = 1 << 16,
        MentionEveryone = 1 << 17,
        UseExternalEmojis = 1 << 18,
        ViewGuildInsights = 1 << 19,
        Connect = 1 << 20,
        Speak = 1 << 21,
        MuteMembers = 1 << 22,
        DeafenMembers = 1 << 23,
        MoveMembers = 1 << 24,
        UseVad = 1 << 25,
        ChangeNickname = 1 << 26,
        ManageNicknames = 1 << 27,
        ManageRoles = 1 << 28,
        ManageWebhooks = 1 << 29,
        ManageGuildExpressions = 1 << 30,
        UseApplicationCommands = 1 << 31,
        RequestToSpeak = 1 << 32,
        ManageEvents = 1 << 33,
        ManageThreads = 1 << 34,
        CreatePublicThreads = 1 << 35,
        CreatePrivateThreads = 1 << 36,
        UseExternalStickers = 1 << 37,
        SendMessagesInThreads = 1 << 38,
        UseEmbeddedActivities = 1 << 39,
        ModerateMembers = 1 << 40,
        ViewCreatorMonetizationAnalytics = 1 << 41,
        UseSoundboard = 1 << 42,
        CreateGuildExpressions = 1 << 43,
        CreateEvents = 1 << 44,
        UseExternalSounds = 1 << 45,
        SendVoiceMessages = 1 << 46,
        SendPolls = 1 << 49,
        UseExternalApps = 1 << 50,
    }
}