name: hiRPC

on: 
  push:
    branches:
      - main
    paths:
      - "hirpc/**/*.json"
      - "hirpc/**/*.js"
      - "hirpc/**/*.ts"
  pull_request:
    branches:
      - main
    paths:
      - "hirpc/**/*.json"
      - "hirpc/**/*.js"
      - "hirpc/**/*.ts"

jobs:
  hirpc_tests:
    name: hiRPC Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./hirpc"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@26

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --loglevel error

      - name: Run tests
        run: pnpm test