name: Unity

on: 
  push:
    branches:
      - main
    paths:
      - "unity/**/*.cs"
  pull_request:
    branches:
      - main
    paths:
      - "unity/**/*.cs"
    types:
      - opened
      - labeled
      - synchronize

jobs:
  unity_tests:
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'ci:ready'))
    name: Unity Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          packageMode: true
          unityVersion: "2021.3.45f1"
          projectPath: unity
          testMode: playmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}